all:
    children:
      deploy-node:
        hosts:
          all-in-one
        vars:
          mariadb_img: bitnami/mariadb:latest
          wordpress_img: bitnami/wordpress:latest
          wordpress_http_port: 8080
          wordpress_https_port: 8443
          mariadb_port: 3306
          network_docker: all-in-one-wordpress
          volume_mariadb: mariadb_persistence
          volume_wordpress: wordpress_persistence
          db_user: pnguyen
          db_name: wordpress_ansible
          db_password: 12345678
          



