---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mariadb
  labels:
    app: wordpress-k8s
spec:
  ports:
    - port 3306
  selector:
    app: wordpress-k8s
    tier: mariadb
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: wordpress-mariadb-volume
  labels:
    app: wordpress-k8s
  spec:
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mariadb
  labels:
    app: wordpress-k8s
spec:
  selector: 
    matchLabels:
      app: wordpress-k8s
      tier: mariadb
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: wordpress-k8s
          tier: mariadb
      spec:
        containers:
        - name: mariadb
          image: bitnami/mariadb:latest
          envFrom:
          - secretRef:
              name: secret-mariadb
        restartPolicy: Never
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb-volume
        mountPath: /var/lib/mariadb
        volumes:
        - name: mariadb-volume
          persistentVolumeClaim:
            claimName: wordpress-mariadb-volume
